// Generated by scripts/sync-content.mjs. Do not edit by hand.
export const curriculumLabs = {
  "1": [
    {
      "fileName": "day1-starter.html",
      "titleEn": "Day 1 starter page",
      "titleKo": "Day 1 시작 페이지"
    }
  ],
  "2": [],
  "3": [
    {
      "fileName": "day3-ai-looking.html",
      "titleEn": "Design diagnosis practice",
      "titleKo": "디자인 진단 실습본"
    },
    {
      "fileName": "day3-refined.html",
      "titleEn": "Refined comparison page",
      "titleKo": "개선 비교본"
    }
  ],
  "4": [
    {
      "fileName": "day4-filter-start.html",
      "titleEn": "Interaction practice starter",
      "titleKo": "상호작용 실습 시작본"
    },
    {
      "fileName": "day4-filter-working.html",
      "titleEn": "Interaction practice reference",
      "titleKo": "상호작용 실습 확인본",
      "student": false
    }
  ],
  "5": [
    {
      "fileName": "day5-test-candidate.html",
      "titleEn": "User-test candidate",
      "titleKo": "사용자 테스트 후보"
    }
  ],
  "6": [
    {
      "fileName": "day5-test-candidate.html",
      "titleEn": "Publish and republish practice file",
      "titleKo": "배포·재배포 실습 파일"
    }
  ]
} as const;
