// Generated by scripts/sync-content.mjs. Do not edit by hand.
export const curriculumLabs = {
  "1": [],
  "2": [
    {
      "fileName": "day2-watch.py",
      "titleEn": "Day 2 recovery reference — polling and memory",
      "titleKo": "Day 2 복구용 참고본 — 폴링과 기억",
      "student": false
    }
  ],
  "3": [
    {
      "fileName": "day3-tools.py",
      "titleEn": "Day 3 recovery reference — tool calling",
      "titleKo": "Day 3 복구용 참고본 — 도구 호출",
      "student": false
    }
  ],
  "4": [
    {
      "fileName": "day4-safe.py",
      "titleEn": "Day 4 recovery reference — failure isolation",
      "titleKo": "Day 4 복구용 참고본 — 실패 격리",
      "student": false
    }
  ],
  "5": [
    {
      "fileName": "day5-mcp-server.py",
      "titleEn": "Day 5 recovery reference — minimal MCP server",
      "titleKo": "Day 5 복구용 참고본 — 최소 MCP 서버",
      "student": false
    }
  ],
  "6": []
} as const;
