export const overviewKorean: Record<string, string> = {
  "Vibe Coding Bootcamp": "바이브 코딩 부트캠프",
  "AI and Your First Prototype": "AI와 첫 프로토타입",
  "What should a person decide and check when AI writes the code?":
    "AI가 코드를 작성할 때 사람은 무엇을 결정하고 확인해야 할까요?",
  "Clear Requests and Debugging": "명확한 요청과 디버깅",
  "How can a request become testable, and how can a failure become useful evidence?":
    "어떻게 요청을 테스트 가능하게 만들고, 실패를 유용한 증거로 바꿀 수 있을까요?",
  "From a Problem to a Project": "문제에서 프로젝트로",
  "How can your own idea become a small, testable project?":
    "나만의 아이디어를 작고 테스트 가능한 프로젝트로 어떻게 발전시킬 수 있을까요?",
  "One Safe Slice": "기능 하나를 안전하게 확장하기",
  "Can you understand a little, extend one slice, and recover safely?":
    "코드를 조금 이해하고, 기능 하나를 확장한 뒤, 문제가 생겨도 안전하게 복구할 수 있을까요?",
  "Test, Learn, and Finish": "테스트하고, 배우고, 완성하기",
  "How can you prove that another person can use what you built?":
    "다른 사람이 내가 만든 것을 사용할 수 있다는 사실을 어떻게 증명할 수 있을까요?",
  "Ship, Showcase, Reflect": "완성하고, 발표하고, 돌아보기",
  "How can you explain your result and your AI collaboration responsibly?":
    "결과물과 AI 협업 과정을 어떻게 책임 있게 설명할 수 있을까요?",

  "Welcome and readiness": "환영 및 준비 확인",
  "Live build demo": "실시간 제작 시연",
  "The human role": "사람의 역할",
  "Safety promise": "안전 약속",
  Break: "휴식",
  "Tools and files": "도구와 파일",
  "Guided first build": "첫 제작 따라 하기",
  "CHECK, FIX, SAVE": "확인하고, 수정하고, 저장하기",
  "Project Studio": "프로젝트 제작 시간",
  "Share and exit ticket": "공유 및 마무리 확인",
  "Day 1 review": "1일차 복습",
  "Vague / clear A–B test": "모호한 요청과 명확한 요청 A/B 테스트",
  "The Prompt Frame": "프롬프트 작성 틀",
  "Context management": "맥락 관리",
  "Debugging demo": "디버깅 시연",
  "Guided lab build": "실습 따라 하기",
  "Compare and exit ticket": "비교 및 마무리 확인",
  "Review and ownership": "복습 및 주도권",
  "Free topic exploration": "자유 주제 탐색",
  "User, problem, success": "사용자, 문제, 성공 기준",
  "MUST 3 / NICE 2": "필수 3개 / 선택 2개",
  "Wireframe and Project Brief": "와이어프레임과 프로젝트 기획서",
  "Plan review and approval": "계획 검토 및 승인",
  "v0 Project Studio": "v0 프로젝트 제작 시간",
  "30-second pitch": "30초 소개",
  "Project status": "프로젝트 상태 확인",
  "Code map": "코드 지도",
  "Event, state, screen, storage": "이벤트, 상태, 화면, 저장소",
  "Sprint and Save Point": "스프린트와 저장 지점",
  "Recovery paths": "복구 방법",
  "Approve one slice": "기능 하나 승인받기",
  "Final checkpoint": "최종 점검",
  "Test strategy": "테스트 전략",
  "Write test cards": "테스트 카드 작성",
  "Two peer-test rounds": "동료 테스트 2회",
  "Sort problems": "문제 분류",
  "Safety and accessibility": "안전성과 접근성",
  "Approve the fix plan": "수정 계획 승인",
  "Backup and demo path": "백업과 데모 경로",
  "Final readiness": "최종 준비 확인",
  "Last blocker fix": "마지막 핵심 문제 해결",
  "Code Freeze": "코드 동결(Code Freeze)",
  "Partner rehearsal": "짝과 발표 연습",
  Showcase: "결과물 발표",
  "Peer feedback": "동료 피드백",
  "Reflection and close": "성찰 및 마무리",

  "What is vibe coding?": "바이브 코딩이란 무엇인가?",
  "A claim is not evidence": "주장은 증거가 아니다",
  "The Build Loop": "빌드 루프",
  "Why safety comes first": "안전이 먼저인 이유",
  "What you will make today": "오늘 만들 결과물",
  "The hottest new programming language": "요즘 가장 주목받는 프로그래밍 언어",
  "One experiment, two requests": "하나의 실험, 두 개의 요청",
  '"It doesn\'t work" teaches nothing':
    "“작동하지 않아요”만으로는 아무것도 알 수 없다",
  "One change at a time": "한 번에 하나씩 변경하기",
  "What you will do today": "오늘 할 일",
  "Where projects really come from": "프로젝트는 어디에서 시작되는가",
  "User, Problem, Success": "사용자, 문제, 성공 기준",
  "Small enough to finish": "끝낼 수 있을 만큼 작게",
  "Draw before you build": "만들기 전에 그려 보기",
  "Three languages, one page": "세 가지 언어로 만드는 하나의 페이지",
  "How your page thinks": "페이지가 작동하는 방식",
  "One safe slice": "안전한 기능 하나",
  "When things break — and today, they will":
    "문제가 생길 때 — 오늘은 분명 생깁니다",
  "What testing can and cannot do": "테스트로 알 수 있는 것과 알 수 없는 것",
  "Four doors into your app": "앱을 테스트하는 네 가지 방법",
  "Other people are the best test equipment": "다른 사람이 최고의 테스트 도구다",
  "Not every bug deserves today": "모든 버그를 오늘 고칠 필요는 없다",
  "Done is a decision": "완료는 하나의 결정이다",
  "The two-minute demo": "2분 데모",
  'Saying "AI helped me" like a professional':
    "“AI의 도움을 받았습니다”를 전문적으로 설명하는 법",
  "After Friday": "금요일 이후",
};

export function getOverviewKorean(english: string) {
  return overviewKorean[english] ?? english;
}
