import type { InteractiveDayPlan } from "./types";

export const day1Plan: InteractiveDayPlan = {
  day: 1,
  title: "AI and Your First Prototype",
  question: "What should a person decide and check when AI writes the code?",
  artifact: "A tested five-promise first page and two safe changes",
  stages: [
    {
      id: "day1-welcome-readiness",
      start: "00:00",
      end: "00:10",
      minutes: 10,
      phase: "TELL",
      title: "Welcome and readiness",
      goal: "Start with a ready tool, folder, and safety signal.",
      studentBrief: [
        "Get your computer and coding tool ready.",
        "Use the side signal to show Green, Yellow, or Red.",
      ],
      teacherCue: [
        "오늘의 결과물과 5단계 루프를 짧게 소개한다.",
        "학생이 막힌 이유를 설명하게 하지 말고 Green, Yellow, Red 신호부터 받는다.",
      ],
      completion:
        "The required tool and folder are open, and every learner shows their current status with the side signal.",
      activities: [
        {
          id: "day1-readiness-check",
          hidden: true,
          kind: "checklist",
          title: "Ready to begin",
          instruction: "Check each item you can confirm now.",
          items: [
            "My computer is on.",
            "My coding tool opens.",
            "I have a folder named day1-first-build.",
            "I will not enter a secret key or private information on this page.",
          ],
          minimum: 4,
        },
      ],
    },
    {
      id: "day1-live-build-demo",
      start: "00:10",
      end: "00:25",
      minutes: 15,
      phase: "WATCH",
      title: "Live build demo",
      goal: "Notice the decisions around AI-generated code.",
      studentBrief: [
        "Watch the full TELL → WATCH → CHECK → FIX → SAVE loop.",
        "Record what the person does, not only what AI does.",
      ],
      teacherCue: [
        "중립 공통 페이지를 처음부터 끝까지 시연한다.",
        "AI 응답보다 목표 확인, 계획 검토, 실제 클릭 테스트, 저장 시점을 소리 내어 말한다.",
      ],
      completion:
        "The learner records the human goal, test evidence, decision, and one claim that still needs testing.",
      activities: [
        {
          id: "day1-demo-watch",
          kind: "short-answer",
          title: "Recover the decisions from the demo",
          instruction:
            "Record the goal, the test evidence, and the decision made after the test.",
          content: [
            "Human goal",
            "Test action and observed evidence",
            "Human decision after the test",
          ],
          minimum: 3,
        },
        {
          id: "day1-demo-human-decision",
          kind: "short-answer",
          title: "Challenge one untested claim",
          instruction:
            "Write one statement from the demo that would still need a real test before you trust it.",
          placeholder: "The claim was... I would test it by...",
          minimum: 1,
        },
      ],
    },
    {
      id: "day1-human-role",
      start: "00:25",
      end: "00:40",
      minutes: 15,
      phase: "CHECK",
      title: "The human role",
      goal: "Separate AI drafting from human responsibility.",
      studentBrief: [
        "AI can draft code.",
        "A person owns the goal, evidence, and decision to keep the result.",
      ],
      teacherCue: [
        "정답을 바로 말하지 말고 각 상황에서 누가 결정해야 하는지 먼저 선택하게 한다.",
        "작동 여부는 채팅 답변이 아니라 브라우저 행동으로 확인한다는 점을 강조한다.",
      ],
      completion: "The learner answers the responsibility choice and writes one testable success statement.",
      activities: [
        {
          id: "day1-role-choice",
          kind: "choice",
          title: "Who owns the decision?",
          instruction: "Choose the best answer.",
          prompt: "AI says the page is finished. Who decides if it really works?",
          options: [
            {
              label: "The person, after a real test",
              value: "person-tests",
              feedback: "Correct. A claim is not evidence.",
            },
            {
              label: "AI, after it reports that its own tests passed",
              value: "ai-decides",
              feedback: "Not yet. A tool report is still a claim until the person runs the real browser test.",
            },
            {
              label: "The person, after reading the generated code but without using the page",
              value: "person-reads",
              feedback: "Not yet. Reading code does not replace observable browser evidence.",
            },
          ],
        },
        {
          id: "day1-success-statement",
          kind: "short-answer",
          title: "Make success visible",
          instruction: "Finish the sentence with something you can see or do.",
          prompt: "Success means...",
          placeholder: "Success means I can...",
          minimum: 1,
        },
      ],
    },
    {
      id: "day1-safety-promise",
      start: "00:40",
      end: "00:55",
      minutes: 15,
      phase: "FIX",
      title: "Safety promise",
      goal: "Replace unsafe habits with clear classroom rules.",
      studentBrief: [
        "Protect secret keys and private information.",
        "Stop and ask when a request changes more than expected.",
      ],
      teacherCue: [
        "실제 API 키나 개인정보를 화면에 입력하지 않게 한다.",
        "안전 규칙을 읽는 데서 끝내지 말고 잘못된 행동을 안전한 행동으로 바꾸게 한다.",
      ],
      completion: "The learner checks all safety promises and corrects the unsafe choice.",
      activities: [
        {
          id: "day1-safety-checklist",
          kind: "checklist",
          title: "My safety promise",
          instruction: "Check each promise.",
          items: [
            "I will not paste a secret key into a page or chat message.",
            "I will not add real personal information.",
            "I will read the plan before files change.",
            "I will stop when AI changes more than I asked.",
          ],
          minimum: 4,
        },
        {
          id: "day1-safety-fix-choice",
          kind: "choice",
          title: "Fix the unsafe action",
          instruction: "Choose the safe next action.",
          prompt: "A secret key appears in a message.",
          options: [
            {
              label: "Stop, hide it, and ask the teacher",
              value: "stop-hide-ask",
              feedback: "Correct. Do not continue or share it.",
            },
            {
              label: "Copy it into the class page",
              value: "copy-page",
              feedback: "Unsafe. A secret key must not be exposed.",
            },
            {
              label: "Send it to a partner",
              value: "send-partner",
              feedback: "Unsafe. Do not share secret keys.",
            },
          ],
        },
      ],
    },
    {
      id: "day1-break",
      start: "00:55",
      end: "01:05",
      minutes: 10,
      phase: "BREAK",
      title: "Break",
      goal: "Rest and return ready for the build.",
      studentBrief: ["Take a break.", "Return when the timer ends."],
      teacherCue: [
        "도구 문제 학생을 별도로 확인하되 휴식 시간을 수업으로 바꾸지 않는다.",
        "종료 1분 전에 복귀 신호를 준다.",
      ],
      completion: "The break timer reaches zero and the learner returns to the workspace.",
      activities: [
        {
          id: "day1-break-timer",
          kind: "timer",
          title: "Break timer",
          instruction: "Pause your work and return when time is up.",
          durationMinutes: 10,
        },
      ],
    },
    {
      id: "day1-tools-files",
      start: "01:05",
      end: "01:25",
      minutes: 20,
      phase: "TELL",
      title: "Tools and files",
      goal: "Know the folder, working file, browser, and Save Point.",
      studentBrief: [
        "Work only in day1-first-build.",
        "Use index.html as the working file.",
      ],
      teacherCue: [
        "폴더, 터미널, AI 도구, 파일, 브라우저의 역할을 실제 화면으로 연결한다.",
        "작업 파일과 Save Point 사본의 차이를 확인한다.",
      ],
      completion: "The learner matches all four tools to their roles and confirms the correct folder.",
      activities: [
        {
          id: "day1-tool-roles",
          kind: "read",
          title: "Four roles",
          instruction: "Read each role before building.",
          content: [
            "Folder: keeps this lab together.",
            "AI coding tool: drafts and changes code.",
            "index.html: the working page.",
            "Browser: gives real test evidence.",
          ],
        },
        {
          id: "day1-correct-location",
          kind: "checklist",
          title: "Confirm the location",
          instruction: "Check the folder and file rules.",
          items: [
            "I am inside day1-first-build.",
            "I will work in index.html.",
            "I will open the file in a browser to test it.",
          ],
          minimum: 3,
        },
      ],
    },
    {
      id: "day1-guided-first-build",
      start: "01:25",
      end: "01:50",
      minutes: 25,
      phase: "STUDIO",
      title: "Guided first build",
      goal: "Build the shared page with one clear, bounded request.",
      studentBrief: [
        "Send one request for the common page.",
        "Read the plan before any file change.",
      ],
      teacherCue: [
        "모든 학생이 같은 중립 공통 페이지를 만든다.",
        "프롬프트를 보내기 전 Success means와 파일 제한을 손가락으로 짚게 한다.",
      ],
      completion: "index.html opens with all five exact promises from the prompt and offline backup.",
      activities: [
        {
          id: "day1-build-prompt",
          kind: "prompt",
          title: "TELL the first build",
          instruction: "Use this request in the coding tool.",
          content: [
            "Create one file named index.html.",
            'Use the title "My First Build".',
            'Show: "I am learning to build, test, and improve with AI."',
            'Add a card titled "Human in Control".',
            'In the card show: "AI can draft. I choose the goal and check the result."',
            'Add a button labeled "Test the page".',
            'On click show: "The button works!"',
            "Use large readable text, one file, and no external library or personal information.",
            "Before changing a file, show a short two-step plan.",
          ],
        },
        {
          id: "day1-watch-plan",
          kind: "watch",
          title: "WATCH the plan",
          instruction: "Check the plan before you allow the change.",
          items: [
            "The plan uses only index.html.",
            "The plan keeps the exact words and button action.",
            "The plan adds no library or personal information.",
          ],
          minimum: 3,
        },
        {
          id: "day1-first-build-check",
          kind: "checklist",
          title: "Open the result",
          instruction: "Open index.html and check the visible result.",
          items: [
            'The title is exactly "My First Build".',
            'The message is exactly "I am learning to build, test, and improve with AI."',
            'The "Human in Control" card shows the exact control statement.',
            'The button is labeled "Test the page".',
            'Clicking it shows "The button works!"',
          ],
          minimum: 5,
        },
      ],
    },
    {
      id: "day1-check-fix-save",
      start: "01:50",
      end: "02:00",
      minutes: 10,
      phase: "SAVE",
      title: "CHECK, FIX, SAVE",
      goal: "Use evidence, repair only one problem, and keep a working copy.",
      studentBrief: [
        "Test before you claim success.",
        "Fix one observed problem, then save a working copy.",
      ],
      teacherCue: [
        "Expected와 Actual을 말하게 한 뒤에만 수정 프롬프트를 쓰게 한다.",
        "모든 테스트가 통과한 학생만 day1-base.html을 만들게 한다.",
      ],
      completion: "The learner records three test results and opens a working day1-base.html.",
      activities: [
        {
          id: "day1-base-tests",
          kind: "test-record",
          title: "CHECK the page",
          instruction: "Run each action and record Expected and Actual.",
          items: [
            "Open index.html — the exact title, message, and Human in Control card are visible.",
            'Click "Test the page" — "The button works!" appears.',
            "Refresh — the page opens and the button works again.",
          ],
          expected: [
            "Every action has an Actual result.",
            "Every passing result is based on a real browser action.",
          ],
          minimum: 3,
        },
        {
          id: "day1-one-fix",
          kind: "prompt",
          optional: true,
          title: "FIX one observed problem",
          instruction: "Use this only if a test fails. Fill all three parts.",
          content: [
            "Action: [what I did]",
            "Expected: [what should happen]",
            "Actual: [what happened]",
            "Fix only this problem in index.html. Keep working parts the same. Tell me what changed.",
          ],
        },
        {
          id: "day1-base-save",
          kind: "checklist",
          title: "SAVE the base",
          instruction: "After all tests pass, create and verify day1-base.html.",
          items: [
            "index.html passes the tests.",
            "day1-base.html exists.",
            "day1-base.html opens.",
            "Its button works.",
          ],
          minimum: 4,
        },
      ],
    },
    {
      id: "day1-project-studio",
      start: "02:00",
      end: "02:50",
      minutes: 50,
      phase: "STUDIO",
      title: "Project Studio",
      goal: "Make two chosen changes through two small tested loops.",
      studentBrief: [
        "Choose two small changes to the common page.",
        "Build and test only one change at a time.",
      ],
      teacherCue: [
        "주제나 기능 예시를 제시하지 않고 학생이 두 가지 작은 변경을 직접 정하게 한다.",
        "첫 변경이 통과하기 전 두 번째 변경을 시작하지 않게 한다.",
      ],
      completion: "Two chosen changes pass their tests, the original button still works, and day1-final-save.html opens.",
      activities: [
        {
          id: "day1-studio-plan",
          kind: "short-answer",
          title: "Plan two safe changes",
          instruction: "For each change, write the goal, success sign, and what must stay the same.",
          prompt: "Change 1 and Change 2",
          placeholder: "Goal... Success means... Keep...",
          minimum: 2,
        },
        {
          id: "day1-studio-build",
          kind: "prompt",
          title: "Run one loop at a time",
          instruction: "Fill this request for one change. Repeat only after the first change passes.",
          content: [
            "Goal: [one small change]",
            "Success means: [what I can see or do]",
            "Keep this the same: [working behavior]",
            "Change only this part in index.html. Use no external library or personal information.",
            "First show a short plan. Then make the change.",
          ],
        },
        {
          id: "day1-studio-tests-save",
          kind: "test-record",
          title: "CHECK, FIX, and SAVE",
          instruction: "Test after each change. Finish by verifying day1-final-save.html.",
          items: [
            "Change 1 does what its success statement says.",
            "Change 2 does what its success statement says.",
            'The original "Test the page" button still works.',
            "No personal information is present.",
            "day1-final-save.html opens and passes the same tests.",
          ],
          minimum: 5,
        },
      ],
    },
    {
      id: "day1-share-exit",
      start: "02:50",
      end: "03:00",
      minutes: 10,
      phase: "SHARE",
      title: "Share and exit ticket",
      goal: "Show evidence and name one human decision.",
      studentBrief: [
        "Show one working action to a partner.",
        "Finish the exit ticket with evidence.",
      ],
      teacherCue: [
        "설명보다 실제 클릭과 결과를 먼저 보여 주게 한다.",
        "종료 신호를 모아 Day 2에서 다시 다룰 문제를 기록한다.",
      ],
      completion: "A partner observes one passing action and the learner submits both exit answers.",
      activities: [
        {
          id: "day1-partner-share",
          kind: "peer",
          title: "Show one proof",
          instruction: "Let a partner choose one action. Run it and show the result.",
          items: [
            "My partner chose the action.",
            "I ran the action in day1-final-save.html.",
            "My partner saw the result.",
          ],
          minimum: 3,
        },
        {
          id: "day1-exit-answer",
          kind: "short-answer",
          title: "Exit ticket",
          instruction: "Answer both lines.",
          prompt: "One human decision I made... One check that proved my page worked...",
          placeholder: "I decided... I proved it by...",
          minimum: 2,
        },
      ],
    },
  ],
};

export const day2Plan: InteractiveDayPlan = {
  day: 2,
  title: "Clear Requests and Debugging",
  question: "How can a request become testable, and how can a failure become useful evidence?",
  artifact: "Prompt Precision Lab, six tests, and a Context Handoff",
  stages: [
    {
      id: "day2-review",
      start: "00:00",
      end: "00:15",
      minutes: 15,
      phase: "CHECK",
      title: "Day 1 review",
      goal: "Recover the five-step loop and verify the Day 1 Save Point.",
      studentBrief: [
        "Recall the loop without notes.",
        "Open the Day 1 final Save Point and test it once.",
      ],
      teacherCue: [
        "학생이 먼저 다섯 단계를 순서대로 복원하게 한다.",
        "Day 1 파일은 수정하지 말고 열기와 한 번의 클릭 테스트만 하게 한다.",
      ],
      completion:
        "The learner records one passing or failing Day 1 test with Action, Expected, and Actual.",
      activities: [
        {
          id: "day2-loop-order",
          hidden: true,
          kind: "short-answer",
          title: "Recall the loop",
          instruction: "Write the five words in order.",
          placeholder: "_____ → _____ → _____ → _____ → _____",
          expected: ["TELL → WATCH → CHECK → FIX → SAVE"],
          minimum: 5,
        },
        {
          id: "day2-day1-test",
          kind: "test-record",
          title: "Verify, do not edit",
          instruction: "Open day1-final-save.html and run one button test.",
          items: [
            "Action: click the original button.",
            'Expected: "The button works!" appears.',
            "Actual: record what appeared.",
          ],
          minimum: 3,
        },
      ],
    },
    {
      id: "day2-ab-test",
      start: "00:15",
      end: "00:35",
      minutes: 20,
      phase: "WATCH",
      title: "Vague / clear A–B test",
      goal: "Compare requests by the evidence they make possible.",
      studentBrief: [
        "Compare a vague request with a clear request.",
        "Judge the goal, limits, and success check.",
      ],
      teacherCue: [
        "A와 B를 같은 조건에서 보여 주고 결과 차이를 관찰하게 한다.",
        "문장이 길어서가 아니라 성공 기준과 제한이 확인 가능해서 명확하다는 점을 이끈다.",
      ],
      completion: "The learner selects the testable request and records two pieces of evidence.",
      activities: [
        {
          id: "day2-ab-choice",
          kind: "choice",
          title: "Which request is testable?",
          instruction: "Choose the request that gives a clear check.",
          options: [
            {
              label: "A — Make this page better.",
              value: "vague-a",
              feedback: "This has no visible success check or limit.",
            },
            {
              label: "B — Change one named part, keep one rule, and pass one named test.",
              value: "clear-b",
              feedback: "Correct. The change and success evidence are bounded.",
            },
          ],
        },
        {
          id: "day2-ab-evidence",
          kind: "short-answer",
          title: "Record the difference",
          instruction: "Write two details that make one request easier to test.",
          placeholder: "It names... It keeps... Success means...",
          minimum: 2,
        },
      ],
    },
    {
      id: "day2-prompt-frame",
      start: "00:35",
      end: "00:55",
      minutes: 20,
      phase: "TELL",
      title: "The Prompt Frame",
      goal: "Turn an intention into a bounded, testable request.",
      studentBrief: [
        "Use all seven parts: Goal, Context, Feature, Rules, Constraints, Do not change, and Success means.",
        "Keep technical limits separate from the working behavior you must protect.",
      ],
      teacherCue: [
        "각 칸을 설명한 뒤 학생이 짧은 문장으로 직접 채우게 한다.",
        "Success means가 브라우저에서 관찰 가능한지 짝과 확인하게 한다.",
      ],
      completion: "Every Prompt Frame field is filled and Success means names an observable result.",
      activities: [
        {
          id: "day2-frame-read",
          kind: "read",
          title: "Read the frame",
          instruction: "Use every line to control the request.",
          content: [
            "Goal — one result.",
            "Context — the current page and file.",
            "Feature — one change.",
            "Rules — exact behavior.",
            "Constraints — technical and safety limits.",
            "Do not change — working behavior to protect.",
            "Success means — an action and visible result.",
          ],
        },
        {
          id: "day2-frame-write",
          kind: "prompt",
          title: "Build a Prompt Frame",
          instruction: "Fill every bracket. Do not send it yet.",
          content: [
            "Goal: [one result]",
            "Context: [current page and file]",
            "Feature: [one change]",
            "Rules: [exact behavior]",
            "Constraints: [technical and safety limits]",
            "Do not change: [working behavior to protect]",
            "Success means: [action and visible result]",
          ],
        },
        {
          id: "day2-frame-check",
          kind: "checklist",
          title: "Check before sending",
          instruction: "Confirm that another person could test your request.",
          items: [
            "The goal is one result.",
            "The current file and behavior are named.",
            "The feature and exact behavior are named.",
            "Technical and safety limits are named.",
            "Working behavior to protect is named.",
            "Success means includes an action and a visible result.",
          ],
          minimum: 6,
        },
      ],
    },
    {
      id: "day2-context-management",
      start: "00:55",
      end: "01:10",
      minutes: 15,
      phase: "SAVE",
      title: "Context management",
      goal: "Create a handoff that can restart work without guessing.",
      studentBrief: [
        "Use Current, Works, Evidence, Next, Keep, and Success.",
        "Do not call an untested claim a fact.",
      ],
      teacherCue: [
        "새 세션은 이전 대화를 자동으로 안다고 가정하지 않게 한다.",
        "이미 작동함, 테스트 증거, 다음 변경, 유지할 항목을 구분한다.",
      ],
      completion: "The learner writes all six Context Handoff parts with one real test record.",
      activities: [
        {
          id: "day2-handoff-read",
          kind: "read",
          title: "Six parts of a handoff",
          instruction: "Keep only useful, verified context.",
          content: [
            "Current: folder, file, and page.",
            "Works: only tested behavior.",
            "Evidence: Action, Expected, Actual.",
            "Next: one change.",
            "Keep: working behavior to protect.",
            "Success: the new test and regression tests.",
          ],
        },
        {
          id: "day2-handoff-draft",
          kind: "short-answer",
          title: "Draft the handoff",
          instruction: "Write one line for each of the six parts.",
          placeholder: "Current... Works... Evidence... Next... Keep... Success...",
          minimum: 6,
        },
        {
          id: "day2-handoff-fact-check",
          kind: "checklist",
          title: "Remove guesses",
          instruction: "Check the draft before you keep it.",
          items: [
            "Every file name is exact.",
            "Every 'works' claim has a test.",
            "The next change is only one change.",
            "Keep names the old behavior to protect.",
            "Success includes the new action and visible result.",
            "Success includes regression tests for protected behavior.",
          ],
          minimum: 6,
        },
      ],
    },
    {
      id: "day2-break",
      start: "01:10",
      end: "01:20",
      minutes: 10,
      phase: "BREAK",
      title: "Break",
      goal: "Rest and return ready to debug.",
      studentBrief: ["Take a break.", "Return when the timer ends."],
      teacherCue: [
        "디버깅 시연 파일을 준비하고 학생의 작업 파일은 건드리지 않는다.",
        "종료 1분 전에 복귀 신호를 준다.",
      ],
      completion: "The break timer reaches zero and the learner returns to the workspace.",
      activities: [
        {
          id: "day2-break-timer",
          kind: "timer",
          title: "Break timer",
          instruction: "Pause your work and return when time is up.",
          durationMinutes: 10,
        },
      ],
    },
    {
      id: "day2-debugging-demo",
      start: "01:20",
      end: "01:40",
      minutes: 20,
      phase: "FIX",
      title: "Debugging demo",
      goal: "Turn one failure into a small, evidence-based fix request.",
      studentBrief: [
        "Reproduce the same failure.",
        "Record Action, Expected, and Actual before asking for a fix.",
      ],
      teacherCue: [
        "오류를 고치기 전에 같은 행동으로 재현한다.",
        "한 번에 첫 번째 실패만 고치고 이전 통과 테스트를 다시 실행한다.",
      ],
      completion: "The learner records Action, Expected, Actual and writes a fix request limited to one failure.",
      activities: [
        {
          id: "day2-debug-watch",
          kind: "watch",
          title: "Watch the evidence order",
          instruction: "Mark each step when the teacher does it.",
          items: [
            "Run one action.",
            "Reproduce the failure.",
            "Write Expected.",
            "Write Actual.",
            "Ask to fix only this problem.",
            "Repeat the failed test and one old test.",
          ],
          minimum: 6,
        },
        {
          id: "day2-debug-record",
          kind: "test-record",
          title: "Record the failure",
          instruction: "Use only what you can observe.",
          items: [
            "Action: what was typed or clicked.",
            "Expected: the exact result wanted.",
            "Actual: the exact result observed.",
          ],
          minimum: 3,
        },
        {
          id: "day2-debug-prompt",
          kind: "prompt",
          title: "Write the FIX",
          instruction: "Fill this request with the recorded evidence.",
          content: [
            "Action: [observed action]",
            "Expected: [exact expected result]",
            "Actual: [exact actual result]",
            "Fix only this problem. Keep all passing behavior the same. Tell me what changed.",
          ],
        },
      ],
    },
    {
      id: "day2-guided-lab",
      start: "01:40",
      end: "02:00",
      minutes: 20,
      phase: "STUDIO",
      title: "Guided lab build",
      goal: "Build the shared Prompt Precision Lab from exact rules.",
      studentBrief: [
        "Build one local index.html.",
        "Read the plan, then test the basic rules.",
      ],
      teacherCue: [
        "day2-prompt-lab 폴더와 index.html 한 파일만 사용하게 한다.",
        "학생이 네 규칙을 읽은 뒤 프롬프트를 보내고 두 기본 테스트를 실제로 실행하게 한다.",
      ],
      completion: "index.html passes the valid-input and empty-input tests, and day2-base.html opens.",
      activities: [
        {
          id: "day2-lab-prompt",
          kind: "prompt",
          title: "TELL the lab rules",
          instruction: "Use this bounded request in day2-prompt-lab.",
          content: [
            'Goal: Create a local page titled "Prompt Precision Lab" that checks one input.',
            "Context: Work in day2-prompt-lab and create only index.html.",
            'Feature: Show the instruction, a text input labeled "Number", and a "Check input" button.',
            'Rules: empty/spaces → "Enter a value."; not a number or not whole → "Use a whole number."; below 1 or above 10 → "Use a number from 1 to 10."; whole number 1–10 → "Accepted: N".',
            "Constraints: Use one local file and no external library, API, login, payment, or personal data.",
            "Do not change: Keep the exact title, labels, four rules, and result messages in this request.",
            'Success means: empty shows "Enter a value."; 5 shows "Accepted: 5"; day2-base.html opens and passes both tests.',
            "Before changing a file, show a short plan mapped to all seven parts.",
          ],
        },
        {
          id: "day2-lab-watch",
          kind: "watch",
          title: "WATCH the plan",
          instruction: "Allow the build only when all checks are true.",
          items: [
            "The plan uses only index.html.",
            "The plan includes all four rules.",
            "The plan adds no external service or personal data.",
          ],
          minimum: 3,
        },
        {
          id: "day2-basic-tests",
          kind: "test-record",
          title: "CHECK and SAVE the base",
          instruction: "Run both tests. When both pass, verify day2-base.html.",
          items: [
            'Enter 5 — "Accepted: 5".',
            'Leave it empty — "Enter a value."',
            "day2-base.html opens and passes both tests.",
          ],
          minimum: 3,
        },
      ],
    },
    {
      id: "day2-project-studio",
      start: "02:00",
      end: "02:50",
      minutes: 50,
      phase: "STUDIO",
      title: "Project Studio",
      goal: "Run six tests, fix with evidence, hand off context, and save the result.",
      studentBrief: [
        "Write Expected before each test.",
        "Fix one failure at a time and retest old rules.",
      ],
      teacherCue: [
        "여섯 입력의 Expected를 먼저 쓰고 Actual은 실제 실행 후 기록하게 한다.",
        "네 규칙이 모두 통과한 학생만 새 세션에서 Context Handoff로 Clear 변경을 진행한다.",
      ],
      completion: "Six test records are complete, the Context Handoff is used, old rules still pass, and day2-final-save.html opens.",
      activities: [
        {
          id: "day2-six-tests",
          kind: "test-record",
          title: "CHECK six inputs",
          instruction: "Write Expected first. Then run each input and record Actual.",
          items: [
            "Empty",
            "abc",
            "2.5",
            "0",
            "1",
            "10",
          ],
          expected: [
            "Enter a value.",
            "Use a whole number.",
            "Use a whole number.",
            "Use a number from 1 to 10.",
            "Accepted: 1",
            "Accepted: 10",
          ],
          minimum: 6,
        },
        {
          id: "day2-studio-fix-handoff",
          kind: "prompt",
          title: "FIX, then hand off",
          instruction: "Fix one failed test. When all rules pass, start a new session with this handoff.",
          content: [
            "Current: day2-prompt-lab / index.html / Prompt Precision Lab.",
            "Works: [tested passing cases].",
            "Evidence: Action [ ], Expected [ ], Actual [ ].",
            'Next: add one "Clear" button that empties the input and result, then returns focus to the input.',
            "Keep: the title, Check input button, four rules, exact messages, layout, and file names.",
            "Success: after any check, Clear empties the input and result, focus returns to the input, and all six old tests still pass.",
          ],
        },
        {
          id: "day2-regression-save",
          kind: "checklist",
          title: "Retest and SAVE",
          instruction: "Check the new action and the old rules, then verify the final copy.",
          items: [
            "Clear empties the input and result and returns focus to the input.",
            "All four old input rules still pass.",
            "Every failed test was repeated after its fix.",
            "At least one old passing test was repeated.",
            "day2-final-save.html opens and passes the same checks.",
          ],
          minimum: 5,
        },
      ],
    },
    {
      id: "day2-compare-exit",
      start: "02:50",
      end: "03:00",
      minutes: 10,
      phase: "SHARE",
      title: "Compare and exit ticket",
      goal: "Compare evidence and leave a reusable debugging record.",
      studentBrief: [
        "Compare one test record with a partner.",
        "Submit the clearest request and the most useful evidence.",
      ],
      teacherCue: [
        "완성도 비교가 아니라 요청과 증거의 명확성을 비교하게 한다.",
        "다음 수업을 위해 Yellow와 Red 원인을 짧게 수집한다.",
      ],
      completion: "A partner confirms one complete test record and the learner submits both exit answers.",
      activities: [
        {
          id: "day2-peer-compare",
          kind: "peer",
          title: "Compare one record",
          instruction: "Show one Action, Expected, Actual record. Your partner checks all three parts.",
          items: [
            "The action is exact.",
            "The expected result is testable.",
            "The actual result is observed, not guessed.",
          ],
          minimum: 3,
        },
        {
          id: "day2-exit-ticket",
          kind: "short-answer",
          title: "Exit ticket",
          instruction: "Answer both lines.",
          prompt: "My clearest request line... My most useful failure evidence...",
          placeholder: "The line was... The evidence was...",
          minimum: 2,
        },
      ],
    },
  ],
};
