import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const sourceRoot = path.resolve(
  projectRoot,
  process.env.CURRICULUM_SOURCE ?? "../교안완성본",
);
const outputDir = path.join(projectRoot, "content");
const outputFile = path.join(outputDir, "generated.ts");
const labsOutputFile = path.join(outputDir, "generated-labs.ts");
const publicLabsDir = path.join(projectRoot, "public", "labs");

const labsByDay = {
  1: [
    {
      fileName: "day1-starter.html",
      titleEn: "Day 1 starter page",
      titleKo: "Day 1 시작 페이지",
    },
  ],
  2: [],
  3: [
    {
      fileName: "day3-ai-looking.html",
      titleEn: "Design diagnosis practice",
      titleKo: "디자인 진단 실습본",
    },
    {
      fileName: "day3-refined.html",
      titleEn: "Refined comparison page",
      titleKo: "개선 비교본",
    },
  ],
  4: [
    {
      fileName: "day4-filter-start.html",
      titleEn: "Interaction practice starter",
      titleKo: "상호작용 실습 시작본",
    },
    {
      fileName: "day4-filter-working.html",
      titleEn: "Interaction practice reference",
      titleKo: "상호작용 실습 확인본",
      student: false,
    },
  ],
  5: [
    {
      fileName: "day5-test-candidate.html",
      titleEn: "User-test candidate",
      titleKo: "사용자 테스트 후보",
    },
  ],
  6: [
    {
      fileName: "day5-test-candidate.html",
      titleEn: "Publish and republish practice file",
      titleKo: "배포·재배포 실습 파일",
    },
  ],
};

async function read(relativePath) {
  return readFile(path.join(sourceRoot, relativePath), "utf8");
}

const days = {};

for (let day = 1; day <= 6; day += 1) {
  const base = `day${day}`;
  const [instructor, lessonEn, lessonKo] = await Promise.all([
    read(`${base}/01-강사교안-ko.md`),
    read(`${base}/02-student-lesson-en.md`),
    read(`${base}/02-student-lesson-ko.md`),
  ]);

  days[day] = {
    instructor,
    lessonEn,
    lessonKo,
    labs: labsByDay[day],
  };
}

const studentSetupEn = `# Start Here — Student Setup Check

- OpenCode opens in the class practice folder.
- NVIDIA is connected and the instructor's class model is selected.
- A safe test request can create \`setup-check.txt\` containing only \`READY\`.
- Never enter an API key, password, student ID, phone number, or other private information on the course website.
- If a key is exposed, revoke it and create a new one.
`;

const studentSetupKo = `# 시작 전 — 학생 설정 확인

- 수업 실습 폴더에서 OpenCode가 실행됩니다.
- NVIDIA가 연결되어 있고 강사가 지정한 수업 모델을 선택했습니다.
- 안전한 테스트 요청으로 \`READY\` 한 줄만 담긴 \`setup-check.txt\`를 만들 수 있습니다.
- 강의 웹사이트에 API 키, 비밀번호, 학번, 전화번호 또는 다른 개인정보를 입력하지 않습니다.
- 키가 노출되면 즉시 폐기하고 새 키를 발급합니다.
`;

const generated = {
  syncedAt: new Date().toISOString(),
  start: {
    student: `${studentSetupEn}\n${studentSetupKo}`,
    studentEn: studentSetupEn,
    studentKo: studentSetupKo,
    instructor: await read("00-강사-사전준비.md"),
  },
  days,
};

await mkdir(publicLabsDir, { recursive: true });
for (const lab of new Map(
  Object.values(labsByDay)
    .flat()
    .map((item) => [item.fileName, item]),
).values()) {
  await copyFile(
    path.join(sourceRoot, "labs", lab.fileName),
    path.join(publicLabsDir, lab.fileName),
  );
}

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputFile,
  `// Generated by scripts/sync-content.mjs. Do not edit by hand.\n` +
    `export const curriculumContent = ${JSON.stringify(generated, null, 2)} as const;\n`,
  "utf8",
);
await writeFile(
  labsOutputFile,
  `// Generated by scripts/sync-content.mjs. Do not edit by hand.\n` +
    `export const curriculumLabs = ${JSON.stringify(labsByDay, null, 2)} as const;\n`,
  "utf8",
);

console.log(`Synced curriculum content to ${path.relative(projectRoot, outputFile)}`);
