import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const sourceRoot = path.resolve(
  projectRoot,
  process.env.CURRICULUM_SOURCE ?? "../교안제작",
);
const outputDir = path.join(projectRoot, "content");
const outputFile = path.join(outputDir, "generated.ts");

async function read(relativePath) {
  return readFile(path.join(sourceRoot, relativePath), "utf8");
}

async function readOptional(relativePath) {
  try {
    return await read(relativePath);
  } catch {
    return "";
  }
}

const days = {};

for (let day = 1; day <= 6; day += 1) {
  const base = `day${day}`;
  days[day] = {
    readme: await read(`${base}/README.md`),
    student: await read(`${base}/02-학생-워크시트-en.md`),
    instructor: await read(`${base}/01-강사-가이드-ko.md`),
    present: await read(`${base}/03-TV-화면-원고.md`),
    cards: await read(`${base}/04-classroom-cards-en.md`),
    lecture: await readOptional(`${base}/07-강의-읽기-en.md`),
  };
}

const generated = {
  syncedAt: new Date().toISOString(),
  start: {
    student: await read("00-start-here/02-setup-completion-card-en.md"),
    instructor: await read("00-start-here/01-세팅-운영-가이드-ko.md"),
  },
  days,
};

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputFile,
  `// Generated by scripts/sync-content.mjs. Do not edit by hand.\n` +
    `export const curriculumContent = ${JSON.stringify(generated, null, 2)} as const;\n`,
  "utf8",
);

console.log(`Synced curriculum content to ${path.relative(projectRoot, outputFile)}`);
